### ISSUE TITLE
forgive me for my limited ability to find the relevant dataset files

### ISSUE THREAD

**Issue by lycr722** [zhangtia16/MolGraph-LarDo#1]
Hello Dear Author, I have read this paper and performed the experiment. The ideas that inspired me and the excellent logical writing intrigued me. But forgive me for my limited ability to find the relevant dataset files, if I have a spare moment I would like to have a response regarding the dataset download and availability. Best wishes.

**Comment by zhangtia16** [comment]
Thank you for your interest in our work. For the datasets, please refer to the MolCLR project, where the author has shared them via Google Drive. You can find the link to the drive here: https://github.com/yuyangw/MolCLR. 

We have currently uploaded only the project's source code and have not yet provided a complete README. We will be updating with a full README and additional code/datasets updates in the future.

**Comment by lycr722** [comment]
Thank you for your recycling. I didn't expect to receive a reply so soon. Thank you for your enthusiasm and responsibility for the work, I will continue to pay attention to you and the project



---Original---
From: "ZHANG ***@***.***&gt;
Date: Wed, Sep 11, 2024 23:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhangtia16/MolGraph-LarDo] forgive me for my limited ability tofind the relevant dataset files (Issue #1)




 
Thank you for your interest in our work. For the datasets, please refer to the MolCLR project, where the author has shared them via Google Drive. You can find the link to the drive here: https://github.com/yuyangw/MolCLR.
 
We have currently uploaded only the project's source code and have not yet provided a complete README. We will be updating with a full README and additional code/datasets updates in the future.
